### ISSUE TITLE
NotImplementedError: cannot instantiate 'PosixPath' on your system

### ISSUE THREAD

**Issue by yogeshhk** [hwchase17/notion-qa#12]
Traceback (most recent call last):
  File "notion-qa-hwchase17\main.py", line 13, in <module>
    store = pickle.load(f)
  File "..\AppData\Local\Continuum\anaconda3\envs\langchain\lib\pathlib.py", line 1084, in __new__
    raise NotImplementedError("cannot instantiate %r on your system"
NotImplementedError: cannot instantiate 'PosixPath' on your system

**Comment by G1213123** [comment]
I added this solution to the main.py and it fixes the problem:
[https://stackoverflow.com/questions/57286486/i-cant-load-my-model-because-i-cant-put-a-posixpath](url)

```
import pathlib
temp = pathlib.PosixPath
pathlib.PosixPath = pathlib.WindowsPath
```

**Comment by DanielThaumazo** [comment]
Worked for me when added to top of qa.py rather than main.py

**Comment by DanielThaumazo** [comment]
The origin of the issue, I think is within faiss_store.pkl, as a reference to a PosixPath is embedded.
