### ISSUE TITLE
faiss.loader: Could not load library with AVX2 support due to

### ISSUE THREAD

**Issue by nsbuttar** [hwchase17/notion-qa#21]
Hi All, 

I have encountered an issue with running the code. Was wondering if someone already has an answer. 

Using Visual Studio Code, python. 

Any help will be greatly appreciated. 

- I have pip installed faiss cpu
=======

2023-04-07 19:01:39.162 INFO    faiss.loader: Loading faiss with AVX2 support.
2023-04-07 19:01:39.162 INFO    faiss.loader: Could not load library with AVX2 support due to:
ModuleNotFoundError("No module named 'faiss.swigfaiss_avx2'")
2023-04-07 19:01:39.163 INFO    faiss.loader: Loading faiss.
2023-04-07 19:01:39.179 INFO    faiss.loader: Successfully loaded faiss.
Traceback (most recent call last):
  File "e:\notion-qa\main.py", line 15, in <module>
    store = pickle.load(f)
            ^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.752.0_x64__qbz5n2kfra8p0\Lib\pathlib.py", line 873, in __new__
    raise NotImplementedError("cannot instantiate %r on your system"
NotImplementedError: cannot instantiate 'PosixPath' on your system

**Comment by xkasberg** [comment]
This is actually a FAISS issue not a Langchain issue
